import React, { useState, useEffect} from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import LSHook from '../components/LSExample';
import {getLocalStorageValue} from '../hooks/useLocalStorage'
import InputValue from '../components/InputValue';

export default function Home() {
  
  const [storageValue, setStorageValue] = useState(false)

  // useEffect(() => {
  //       return localStorage.length > 0 ? setStorageValue(true) : false;
  //   }, [])

  useEffect(() => {
        return getLocalStorageValue('task') ? setStorageValue(true) : false;
    }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Custom Hook.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        Custom useLocalStorage Hook for realtime data fetching.
        </h1>
        <div className='mt-4'>
          <LSHook/>
        </div>
      </main>
    </div>
  )
}
